name: tg_bot_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  televerse: ^1.13.2
  shelf: ^1.4.1
  sembast:
  cron: ^0.6.0

dev_dependencies:
  #lints: ^2.1.0
  test: ^1.24.0
